package com.example.kashtakala.fragments

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import com.example.kashtakala.databinding.FragmentEstimatorBinding
import com.example.kashtakala.viewmodels.MainViewModel
import java.util.Locale

class EstimatorFragment : Fragment() {

    private var _binding: FragmentEstimatorBinding? = null
    private val binding get() = _binding!!
    private val viewModel: MainViewModel by activityViewModels()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentEstimatorBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val length = arguments?.getFloat("length", 0.0f) ?: 0.0f
        val width = arguments?.getFloat("width", 0.0f) ?: 0.0f
        val height = arguments?.getFloat("height", 0.0f) ?: 0.0f

        if (length > 0) binding.etLength.setText(String.format(Locale.getDefault(), "%.1f", length))
        if (width > 0) binding.etWidth.setText(String.format(Locale.getDefault(), "%.1f", width))
        if (height > 0) binding.etHeight.setText(String.format(Locale.getDefault(), "%.1f", height))

        if (length > 0 && width > 0 && height > 0) {
            calculateEstimation()
        }

        binding.btnCalculate.setOnClickListener {
            calculateEstimation()
        }

        binding.btnShareEstimate.setOnClickListener {
            shareFullEstimate()
        }
    }

    private fun calculateEstimation() {
        val lStr = binding.etLength.text.toString()
        val wStr = binding.etWidth.text.toString()
        val hStr = binding.etHeight.text.toString()

        if (lStr.isNotEmpty() && wStr.isNotEmpty() && hStr.isNotEmpty()) {
            val l = lStr.toDouble()
            val w = wStr.toDouble()
            val h = hStr.toDouble()

            val sqFt = 2 * (l * w + w * h + h * l)
            val vol = l * w * h
            val estimatedCost = sqFt * 500.0

            binding.cardResults.visibility = View.VISIBLE
            binding.tvArea.text = String.format(Locale.getDefault(), "Total Surface: %.2f Sq. Ft.", sqFt)
            binding.tvVolume.text = String.format(Locale.getDefault(), "Volume: %.2f Cu. Ft.", vol)
            binding.tvRequirement.text = String.format(Locale.getDefault(), "Est. Material Cost: ₹%,.0f", estimatedCost)

            viewModel.currentMaterialEstimate.value = estimatedCost
        }
    }

    private fun shareFullEstimate() {
        val l = binding.etLength.text.toString()
        val w = binding.etWidth.text.toString()
        val h = binding.etHeight.text.toString()
        val area = binding.tvArea.text.toString()
        val vol = binding.tvVolume.text.toString()
        val cost = binding.tvRequirement.text.toString()

        val shareText = """
            🏠 *KashtaKala Material Estimate*
            ----------------------------------
            📏 Dimensions: ${l}ft x ${w}ft x ${h}ft
            📐 $area
            📦 $vol
            💰 $cost
            ----------------------------------
            Generated by KashtaKala App
        """.trimIndent()

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Furniture Material Estimate")
            putExtra(Intent.EXTRA_TEXT, shareText)
        }
        startActivity(Intent.createChooser(intent, "Share Estimate via"))
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
